name: "Build LaTeX PDF"
description: "Compile LaTeX .tex files into PDF or other formats using the basemax/latex-builder Docker image."
author: "Seyyed Ali Mohammadiyeh (Max Base)"
branding:
  icon: "file-text"
  color: "blue"

inputs:
  tex_path:
    description: "Path to the input .tex file."
    required: true

  build_format:
    description: "Output build format: pdf, dvi, ps, slides, beamer, clean."
    required: false
    default: "pdf"

  output_path:
    description: "Optional custom output PDF filename."
    required: false
    default: ""

outputs:
  pdf:
    description: "Path to generated PDF file."

runs:
  using: "composite"
  steps:
    - name: Prepare build variables
      shell: bash
      run: |
        TEX="${{ inputs.tex_path }}"
        FORMAT="${{ inputs.build_format }}"

        if [ ! -f "$TEX" ]; then
          echo "::error::TEX file not found: $TEX"
          exit 1
        fi

        BASENAME=$(basename "$TEX" .tex)

        if [ -z "${{ inputs.output_path }}" ]; then
          OUTPDF="${BASENAME}.pdf"
        else
          OUTPDF="${{ inputs.output_path }}"
        fi

        echo "TEX_FILE=$TEX" >> $GITHUB_ENV
        echo "BUILD_FORMAT=$FORMAT" >> $GITHUB_ENV
        echo "OUTPDF=$OUTPDF" >> $GITHUB_ENV

    - name: Run LaTeX using basemax/latex-builder
      shell: bash
      run: |
        docker run --rm \
          -v "${{ github.workspace }}:/work" \
          -e TEX_FILE="${{ env.TEX_FILE }}" \
          -e BUILD_FORMAT="${{ env.BUILD_FORMAT }}" \
          -w /work \
          basemax/latex-builder:latest

        if [ "${{ env.BUILD_FORMAT }}" != "clean" ]; then
          mv "${{ env.TEX_FILE%.tex }}.pdf" "${{ env.OUTPDF }}"
        fi

        echo "pdf=${{ env.OUTPDF }}" >> $GITHUB_OUTPUT
